name: Build

on:
  push:
    branches-ignore:
      - next
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Cache
        uses: actions/cache@v1.0.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build
      - name: yarn install, build, and test
        run: |
          yarn ci
          yarn test
        env:
          CI: true
